# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\src\RPAChallengeInputForms'
    orchestratorConnection: 'Orchestrator External Application Connection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Packages\RPAChallengeInputForms'
    outputType: 'None'
    runWorkflowAnalysis: true
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator External Application Connection'
    folderName: 'Shared'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'UiPathBuildPipeline'
    publishLocation: 'Container'